"""Auto-generated by port_consts_offsets.py. Do not hand-edit.
Ported from reference_preconsts.swf to s4.swf.
Offsets are ActionPush operand positions in the target baseline.
"""

DRAWING = [
    (28094002, 'i', 0xFFFFFF, 0x111415, 'insetBox headClr fallback'),
    (28094083, 'i', 0xFFFFFF, 0x14171A, 'insetBox winClr fallback'),
    (28095674, 'i', 0xFFFFFF, 0x111415, 'insetBoxBuddies headClr fallback'),
    (28095755, 'i', 0xFFFFFF, 0x14171A, 'insetBoxBuddies winClr fallback'),
]

CONSOLE = [
    (28203818, 'i', 0x7084A9, 0x111415, 'converse panel header'),
    (28203813, 'i', 0x3D5E99, 0x202629, 'converse panel body top'),
    (28203808, 'i', 0x0C1931, 0x090B0C, 'converse panel body bottom'),
    (28204097, 'i', 0xFFFFFF, 0x202629, 'converse buddy-name strip'),
    (28205278, 'i', 0x5B6675, 0xC8D0DA, 'txt_buddyname (was dark on white strip)'),
    (28207584, 'i', 0xADBDD9, 0x2E353D, 'inbox divider rule'),
    (28210797, 'i', 0xFFFFFF, 0x202629, 'infoClip tab'),
    (28210965, 'i', 0xAEBBCF, 0x202629, 'infoClip body top'),
    (28210970, 'i', 0xAEBBCF, 0x14171A, 'infoClip body bottom'),
    (28211952, 'i', 0x5B6675, 0xC8D0DA, 'infoClip name_txt'),
    (28212429, 'i', 0x425166, 0x98A2AE, 'infoClip loc_txt (offline)'),
    (28226163, 'i', 0xFFFFFF, 0x202629, 'request infoClip tab'),
    (28226331, 'i', 0xAEBBCF, 0x202629, 'request infoClip body top'),
    (28226336, 'i', 0xAEBBCF, 0x14171A, 'request infoClip body bottom'),
    (28227318, 'i', 0x5B6675, 0xC8D0DA, 'request infoClip name_txt'),
    (28228896, 'i', 0xFFFFFF, 0x202629, 'outgoing infoClip tab'),
    (28229064, 'i', 0xAEBBCF, 0x202629, 'outgoing infoClip body top'),
    (28229069, 'i', 0xAEBBCF, 0x14171A, 'outgoing infoClip body bottom'),
    (28230051, 'i', 0x5B6675, 0xC8D0DA, 'outgoing infoClip name_txt'),
    (28220140, 'i', 0x7084A9, 0x111415, 'buddy list header'),
    (28220135, 'i', 0xB3CCF0, 0x202629, 'buddy list body top'),
    (28220130, 'i', 0x93A8C9, 0x090B0C, 'buddy list body bottom'),
    (28221754, 'i', 0x7084A9, 0x111415, 'buddy list header (tabbed)'),
    (28221749, 'i', 0xB3CCF0, 0x202629, 'buddy list body top (tabbed)'),
    (28221744, 'i', 0x93A8C9, 0x090B0C, 'buddy list body bottom (tabbed)'),
]

EMAIL = [
    (28169222, 'i', 0xFFFFFF, 0x14171A, 'ctWhite: unselected row bg / selected row text'),
    (28169269, 'd', 0.0, 0xC8D0DA, 'ctBlack: unselected row text'),
    (28169320, 'i', 0x7FCCFF, 0xFF3823, 'ctHi: selected row bg'),
    (28156971, 'i', 0x8291A9, 0x111415, 'inbox insetBox header'),
    (28157132, 'i', 0xA9BAD5, 0x202629, 'inbox tab column block'),
    (28157362, 'i', 0xFFFFFF, 0x111415, 'inbox tab strip'),
    (28158075, 'i', 0xD0D8E6, 0x2E353D, 'sort header top rule'),
    (28158264, 'i', 0xA2B1CC, 0x202629, 'sort header band'),
    (28158471, 'i', 0x9FA1A4, 0x2E353D, 'sort header bottom rule'),
    (28158808, 'i', 0xFFFFFF, 0x090B0C, 'list/view separator outer'),
    (28158993, 'i', 0xADBDD9, 0x2E353D, 'list/view separator inner'),
    (28167264, 'i', 0xFFFFFF, 0x14171A, 'row hilite fill'),
    (28167516, 'i', 0xADBDD9, 0x2E353D, 'row separator line'),
    (28168570, 'd', 0.0, 0xC8D0DA, 'fld_from'),
    (28162494, 'i', 0xA9BAD5, 0x111415, 'compose insetBox header'),
    (28162747, 'i', 0xFFFFFF, 0x202629, 'compose To field bg'),
    (28163368, 'd', 0.0, 0xC8D0DA, 'compose To text'),
    (28163461, 'i', 0xFFFFFF, 0x202629, 'compose Subject field bg'),
    (28164109, 'd', 0.0, 0xC8D0DA, 'compose Subject text'),
    (28164475, 'd', 0.0, 0xC8D0DA, 'compose Message text'),
    (28171941, 'd', 0.0, 0xC8D0DA, 'msgArea body text'),
]

OWNERS = [
    (b'newConsoleWindow', DRAWING, 'Drawing'),
    (b'buddyHeaderH', CONSOLE, 'Console'),
    (b'convertTimestamp', EMAIL, 'Email'),
]
