"""Re-derive dark_ui_consts offsets for a different baseline SWF.

Usage: python port_consts_offsets.py <reference.swf> <target.swf> <out_table.py>

The offsets in dark_ui_consts.py are absolute byte positions taken from one
specific build. Any baseline whose classes were recompiled shifts them, and
apply_dark_ui_consts.py then refuses to run (which is the correct behaviour --
it asserts the old value before writing).

Porting works because the edits are identified by more than an offset: each is
"the Nth ActionPush of value V inside class C". This script resolves that
ordinal in the reference build, then finds the same ordinal in the target and
emits a fresh table.

An entry is only ported when the count of pushes of V in C is IDENTICAL in both
builds. If the recompile changed how many times a value appears, the ordinal is
no longer meaningful and the entry is dropped with a warning rather than
guessed at. Nothing here writes to a SWF -- apply_dark_ui_consts.py still
re-asserts every old value before it patches.
"""
from __future__ import annotations

import importlib
import os
import struct
import sys
from pathlib import Path

import pcodemap
import swf_theme_lib as swfimg

ACTION_PUSH = 0x96
PUSH_SIZES = {1: 4, 2: 0, 3: 0, 4: 1, 5: 1, 6: 8, 7: 4, 8: 1, 9: 2}


def push_sites(body: bytes, start: int, end: int):
    """-> list of (operand_offset, kind, value) for every push in [start, end)."""
    sites = []
    i = start + 2  # DoInitAction opens with a UI16 sprite id
    while i < end:
        op = body[i]
        if op < 0x80:
            i += 1
            continue
        if i + 3 > end:
            break
        length = struct.unpack_from("<H", body, i + 1)[0]
        a, b = i + 3, i + 3 + length
        if b > end:
            break
        if op == ACTION_PUSH:
            j = a
            while j < b:
                ptype = body[j]
                if ptype == 0:
                    k = body.find(b"\x00", j + 1, b)
                    if k < 0:
                        break
                    j = k + 1
                    continue
                size = PUSH_SIZES.get(ptype)
                if size is None:
                    break
                if ptype == 7:
                    sites.append((j, "i", struct.unpack_from("<i", body, j + 1)[0]))
                elif ptype == 6:
                    sites.append((j, "d", pcodemap.unpack_double(bytes(body[j + 1:j + 9]))))
                j += 1 + size
        i = b
    return sites


def main():
    ref_p, tgt_p, out_p = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
    cfg = importlib.import_module(os.environ.get("DARKUI_CONSTS", "dark_ui_consts"))

    _, _, ref_body, ref_ts = swfimg.read_swf(ref_p)
    _, _, tgt_body, tgt_ts = swfimg.read_swf(tgt_p)
    ref_body, tgt_body = bytes(ref_body), bytes(tgt_body)

    blocks, ported, dropped = [], 0, []
    for marker, edits, name in cfg.OWNERS:
        r = pcodemap.find_class_tag(ref_body, ref_ts, marker)
        t = pcodemap.find_class_tag(tgt_body, tgt_ts, marker)
        r_sites = push_sites(ref_body, r.payload_start, r.payload_end)
        t_sites = push_sites(tgt_body, t.payload_start, t.payload_end)
        print(f"\n{name}: reference {r.payload_end - r.payload_start:,} bytes "
              f"({len(r_sites):,} pushes) -> target "
              f"{t.payload_end - t.payload_start:,} bytes ({len(t_sites):,} pushes)")

        lines = []
        for off, kind, old, new, note in edits:
            r_match = [s for s in r_sites if s[1] == kind and s[2] == old]
            t_match = [s for s in t_sites if s[1] == kind and s[2] == old]
            hit = [i for i, s in enumerate(r_match) if s[0] == off]
            if not hit:
                dropped.append((name, note, f"offset {off:,} not a push of {old!r} in reference"))
                continue
            ordinal = hit[0]
            if len(r_match) != len(t_match):
                dropped.append((name, note,
                                f"value occurs {len(r_match)}x in reference but "
                                f"{len(t_match)}x in target -- ordinal unsafe"))
                continue
            new_off = t_match[ordinal][0]
            val = f"0x{old:06X}" if kind == "i" else repr(old)
            lines.append(f"    ({new_off}, {kind!r}, {val}, 0x{new:06X}, {note!r}),")
            ported += 1
            print(f"   {off:>12,} -> {new_off:>12,}  [#{ordinal}] {note}")
        blocks.append((name, lines))

    var = {}
    body_out = ['"""Auto-generated by port_consts_offsets.py. Do not hand-edit.',
                f'Ported from {ref_p.name} to {tgt_p.name}.',
                'Offsets are ActionPush operand positions in the target baseline.',
                '"""', '']
    for name, lines in blocks:
        v = name.upper().replace(" ", "_")
        var[name] = v
        body_out.append(f"{v} = [")
        body_out.extend(lines)
        body_out.append("]")
        body_out.append("")
    body_out.append("OWNERS = [")
    for (marker, _, name), (n2, _) in zip(cfg.OWNERS, blocks):
        body_out.append(f"    ({marker!r}, {var[name]}, {name!r}),")
    body_out.append("]")
    out_p.write_text("\n".join(body_out) + "\n", encoding="utf-8")

    print(f"\nported {ported} / {sum(len(e) for _, e, _ in cfg.OWNERS)} edits -> {out_p}")
    if dropped:
        print(f"\n{len(dropped)} edit(s) DROPPED (not ported):")
        for name, note, why in dropped:
            print(f"   {name}: {note}\n      {why}")


if __name__ == "__main__":
    main()
